services:
  app:
    container_name: "estoque_ms"
    build:
      context: ./
      target: prod
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

    depends_on:
      - db
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"

  db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
